---
# Ansible Galaxy requirements
# Install with: ansible-galaxy collection install -r requirements.yml

collections: []
# No external Ansible collections required for this feature
# Using only ansible.builtin modules
