---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  vars:
    # Directory on remote host for benchmark execution. PWD may not work with WSL
    workspace_root: "{{ lookup('env', 'PWD') }}"